INSERT INTO workouts (title, link, user_id, is_favourited) VALUES ('Yoga: Vinyasa Flow(20min)', 'https://www.youtube.com/embed/6ughUyUmKEo', 1, true);
INSERT INTO workouts (title, link, user_id, is_favourited) VALUES ('Full Body Yoga: Vinyasa Flow (30min)', 'https://www.youtube.com/embed/KEYSO-Tc2Go?start=1', 1, true);
INSERT INTO workouts (title, link, user_id, is_favourited) VALUES ('Full Body Yoga: Vinyasa Flow (30min)', 'https://www.youtube.com/embed/KEYSO-Tc2Go?start=1', 1, true);
INSERT INTO workouts (title, link, user_id, is_favourited) VALUES ('Full Body Yoga: Vinyasa Flow (30min)', 'https://www.youtube.com/embed/KEYSO-Tc2Go?start=1', 1, true);
INSERT INTO workouts (title, link, user_id, is_favourited) VALUES ('Full Body Yoga: Vinyasa Flow (30min)', 'https://www.youtube.com/embed/KEYSO-Tc2Go?start=1', 1, true);
INSERT INTO workouts (title, link, user_id) VALUES ('Full Body Yoga: Vinyasa Flow (30min)', 'https://www.youtube.com/embed/KEYSO-Tc2Go?start=1', 1);
INSERT INTO workouts (title, link, user_id) VALUES ('Full Body Yoga: Vinyasa Flow (30min)', 'https://www.youtube.com/embed/KEYSO-Tc2Go?start=1', 1);
INSERT INTO workouts (title, link, user_id) VALUES ('Full Body Yoga: Vinyasa Flow (30min)', 'https://www.youtube.com/embed/KEYSO-Tc2Go?start=1', 1);
INSERT INTO workouts (title, link, user_id) VALUES ('Full Body Yoga: Vinyasa Flow (30min)', 'https://www.youtube.com/embed/KEYSO-Tc2Go?start=1', 1);
INSERT INTO workouts (title, link, user_id) VALUES ('Full Body Yoga: Vinyasa Flow (30min)', 'https://www.youtube.com/embed/KEYSO-Tc2Go?start=1', 1);
