INSERT INTO workouts (title, link, user_id) VALUES ('Vinyasa Flow Yoga (20min)', 'https://www.youtube.com/embed/6ughUyUmKEo', 1);
INSERT INTO workouts (title, link, user_id) VALUES ('Full Body Vinyasa Flow (30min)', 'https://www.youtube.com/embed/KEYSO-Tc2Go?start=1', 1);
INSERT INTO workouts (title, link, user_id) VALUES ('Full Body Vinyasa Flow (30min)', 'https://www.youtube.com/embed/KEYSO-Tc2Go?start=1', 1);
INSERT INTO workouts (title, link, user_id) VALUES ('Full Body Vinyasa Flow (30min)', 'https://www.youtube.com/embed/KEYSO-Tc2Go?start=1', 1);
INSERT INTO workouts (title, link, user_id) VALUES ('Full Body Vinyasa Flow (30min)', 'https://www.youtube.com/embed/KEYSO-Tc2Go?start=1', 1);
INSERT INTO workouts (title, link, user_id) VALUES ('Full Body Vinyasa Flow (30min)', 'https://www.youtube.com/embed/KEYSO-Tc2Go?start=1', 1);
INSERT INTO workouts (title, link, user_id) VALUES ('Full Body Vinyasa Flow (30min)', 'https://www.youtube.com/embed/KEYSO-Tc2Go?start=1', 1);
INSERT INTO workouts (title, link, user_id) VALUES ('Full Body Vinyasa Flow (30min)', 'https://www.youtube.com/embed/KEYSO-Tc2Go?start=1', 1);
INSERT INTO workouts (title, link, user_id) VALUES ('Full Body Vinyasa Flow (30min)', 'https://www.youtube.com/embed/KEYSO-Tc2Go?start=1', 1);
INSERT INTO workouts (title, link, user_id) VALUES ('Full Body Vinyasa Flow (30min)', 'https://www.youtube.com/embed/KEYSO-Tc2Go?start=1', 1);
