INSERT INTO journal_entries (user_id, created_at, answer_one, answer_two, answer_three, result) VALUES (1, '2020-12-1', 'I am always so inspired by all the hard work and determination of my fellow classmates.','I completed my final presentation and it went smoothly. (fingers crossed)', 'Three things I am grateful for are my health, my family and my friends. Especially with christmas around the corner.', TRUE);

INSERT INTO journal_entries (user_id, created_at, answer_one, answer_two, answer_three, result) VALUES (1, '2020-12-2','I would say my greatest qualities are my determination, my kindness and of course my good looks.', 'Looking forward to telling everyone that will listen that I am officially a web developer.', 'Andy''s funny jokes, Travis''s soothing voice, and coffee because coffee.', FALSE);

INSERT INTO journal_entries (user_id, created_at, answer_one, answer_two, answer_three, result) VALUES (1, '2020-12-5','My greatest qualities are my ability to see the positive in any situation. I am also very patient and understanding.', 'I am looking forward to seeing my friends after three months of bootcamp and almost isolation from the world.', 'I am grateful for my friends I have met along the way through bootcamp who made it all possible. Also my family as well as my good health.', FALSE);

INSERT INTO journal_entries (user_id, created_at, answer_one, answer_two, answer_three, result) VALUES (1, '2020-12-29', 'I am inspired by my cohorts ability to focus and get shit done. Who ever thought 12-hour work days would be totally do able.', 'I did all my laundry and vacuumed the whole apartment. My place feels much more put together.', 'Friends & family who stick by me even when I complain about bootcamp, sunny days and time off.', TRUE);

INSERT INTO journal_entries (user_id, created_at, answer_one, answer_two, answer_three, result) VALUES (1, '2020-12-30', 'My greatest qualities are my stellar personality, my ability to always see the brighter side of things as well as my comedic timing.', 'I am looking forward to days off just hanging out, watching christmas movies, drinking mochas in christmas pajamas.', 'I am most grateful for Santa Claus, mochas, and puppies, because puppies make the world a better place. Always.', FALSE);
INSERT INTO journal_entries (user_id, created_at, answer_one, answer_two, answer_three, result) VALUES (1, '2020-12-3', 'Funny, smart and incredibly good looking.', 'Freedom', 'Andy, Andy and Andy', FALSE);
INSERT INTO journal_entries (user_id, created_at, answer_one, answer_two, answer_three, result) VALUES (1, '2020-12-4', 'I am inspired by my cohorts ability to focus and get shit done. Who ever thought 12-hour work days would be totally do able.', 'I am looking forward to days off just hanging out, watching christmas movies, drinking mochas in christmas pajamas.', 'I am most grateful for Santa Claus, mochas, and puppies, because puppies make the world a better place. Always.', FALSE);