DROP TABLE IF EXISTS meditations CASCADE;

CREATE TABLE meditations (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  link TEXT NOT NULL,
  name VARCHAR (255) NOT NULL
);