DROP TABLE IF EXISTS tasks CASCADE;

CREATE TABLE tasks(
    id SERIAL PRIMARY KEY NOT NULL,
    task VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);