DROP TABLE IF EXISTS workouts CASCADE;
CREATE TABLE workouts (
  id SERIAL PRIMARY KEY NOT NULL, 
  name VARCHAR(255) NOT NULL,
  link TEXT NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);