DROP TABLE IF EXISTS quotes CASCADE;

CREATE TABLE quotes(
    id SERIAL PRIMARY KEY NOT NULL,
    content TEXT NOT NULL,
    author VARCHAR(255),
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    is_favourited BOOLEAN DEFAULT FALSE
);